package ch.grisu118.userscript.leitstellenspiel

import ch.grisu118.userscript.leitstellenspiel.model.VehicleGroup

object LSSData {

  val buildings = arrayOf(
    "Feuerwache",
    "Feuerwehrschule",
    "Rettungswache",
    "Rettungsschule",
    "Krankenhaus",
    "Rettungshubschrauber-Station",
    "Polizeiwache",
    "Leitstelle",
    "Polizeischule",
    "THW",
    "THW Schule",
    "Bereitschaftspolizei",
    "Schnelleinsatzgruppe (SEG)",
    "Polizeihubschrauber-Station",
    "Bereitstellungsraum",
    "Wasserrettung"
  )

  val vehicles = arrayOf(
    "LF 20",
    "LF 10",
    "DLK 23",
    "ELW 1",
    "RW",
    "GW-A",
    "LF 8/6",
    "LF 20/16",
    "LF 10/6",
    "LF 16-TS",
    "GW-Öl",
    "GW-L2-Wasser",
    "GW-Messtechnik",
    "SW 1000",
    "SW 2000",
    "SW 2000-Tr",
    "SW KatS",
    "TLF 2000",
    "TLF 3000",
    "TLF 8/8",
    "TLF 8/18",
    "TLF 16/24-Tr",
    "TLF 16/25",
    "TLF 16/45",
    "TLF 20/40",
    "TLF 20/40-SL",
    "TLF 16",
    "GW-Gefahrgut",
    "RTW",
    "NEF",
    "HLF 20",
    "RTH",
    "FuStW",
    "GW-Höhenrettung",
    "ELW 2",
    "leBefKw",
    "MTW",
    "TSF-W",
    "KTW",
    "GKW",
    "MTW-TZ",
    "MzKW",
    "LKW K9",
    "BRmG R",
    "Anh. DLE",
    "MLW 5",
    "WLF",
    "AB-Rüst",
    "AB-Atemschutz",
    "AB-Öl",
    "GruKw",
    "FüKw",
    "GefKw",
    "GW Dekon-P",
    "AB-Dekon-P",
    "KdoW-LNA",
    "KdoW-OrgL",
    "Kran",
    "KTW Typ B",
    "ELW 1 (SEG)",
    "GW-SAN",
    "Polizeihubschrauber",
    "AB-Schlauch",
    "GW-Taucher",
    "GW-Wasserrettung",
    "LKW 7 Lkr 19 tm",
    "Anh MzB",
    "Anh SchlB",
    "Anh MzAB",
    "Tauchkraftwagen",
    "MZB",
    "AB-MZB"
  )

  val vehicleGroups = arrayOf(
    VehicleGroup("Löschfahrzeuge", arrayOf(0, 1, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37)),
    VehicleGroup("Schlauchwagen", arrayOf(11, 13, 14, 15, 16)),
    VehicleGroup("Rüstfahrzeuge", arrayOf(4, 30)))

  val grisu118 = 650
}