export enum BuildingType {
  FIRE_STATION,
  FIRE_ACADEMY,
  MEDIC_STATION,
  MEDIC_ACADEMY,
  HOSPITAL,
  MEDICAL_HELICOPTER_STATION,
  POLICE_STATION,
  DISPATCH_CENTER,
  POLICE_ACADEMY,
  THW_STATION,
  THW_ACADEMY,
  FEDERAL_POLICE_STATION,
  // TODO
}
